name: Dependent job execution
on: workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout the Code
     run: echo "clone the repo"
   - name: Build the Code
     run: echo "maven package command"
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Deploy the build code 
     run: echo "deploy code..."
